### PR TITLE
Only run docker login if credentials are provided via secrets

### PR DESCRIPTION
**Pull request by thepoppingone**
[PFMENG-620]

[PFMENG-620]: https://sph.atlassian.net/browse/PFMENG-620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by lawliet89** [comment]
How about adding `if` to check if those two secrets are non-empty?

**Comment by thepoppingone** [comment]
image
@lawliet89 github not so smart :(

**Comment by thepoppingone** [comment]
https://github.com/orgs/community/discussions/26726

**Comment by thepoppingone** [comment]
oh found the method
```
- name: myjob
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        if: env.MY_SECRET != null
        run: echo "running"
        ```

**Review by lawliet89 — APPROVED** [review]

**Pull request merged**
