### PR TITLE
Remove shellcheck from tf format checks

### PR DESCRIPTION
**Pull request by thepoppingone**

### CODE REVIEW

**Review by shisheng10 — APPROVED** [review]
LGTM

**Review by gowripadmajas — APPROVED** [review]

**Comment by lawliet89** [comment]
Why remove?

**Comment by gowripadmajas** [comment]
Screenshot 2023-09-13 at 4 23 15 PM
facing this, at the moment

**Comment by thepoppingone** [comment]
@lawliet89 shellcheck is not used for checking Terraform related issues, and also... the self hosted runners dont have `shellcheck` installed 😅  

If you think we should include then let me modify the workflow to install this

**Comment by lawliet89** [comment]
👍🏽 

Makes sense in the context of purely Terraform code. If someone is writing shell scripts, then I would say shellcheck is a must.

**Pull request merged**
